import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { COLORS, REFRESH_STEPS } from '../constants';
import { styles } from '../styles';
import type { AppTab, CrisisDataState, HomePhase, LayerKey } from '../types';
import CrisisMap from '../components/CrisisMap';
import ChatPrompt from '../components/ChatPrompt';
import { ActionItem, ChangeItem, Divider, InfoBlock, SectionLabel, SourceTag, StatusBadge } from '../components/common';

const defaultLayers: Record<LayerKey, boolean> = {
  myLocation: true,
  weatherAlerts: true,
  wildfires: true,
  evacWarning: false,
  evacOrder: false,
};

function locationLabel(data: CrisisDataState) {
  const location = data.snapshot?.location;
  return location
    ? `${location.latitude.toFixed(4)}, ${location.longitude.toFixed(4)}`
    : data.locationError ?? 'Getting your location';
}

function syncLabel(data: CrisisDataState) {
  if (data.loading) return 'Refreshing official sources';
  if (!data.snapshot) return 'No live data available';
  return `${data.snapshot.stale ? 'Last available data' : 'Updated'} ${new Date(data.snapshot.fetchedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}`;
}

export default function HomeScreen({
  phase,
  setPhase,
  onNavigate,
  crisisData,
}: {
  phase: HomePhase;
  setPhase: (phase: HomePhase) => void;
  onNavigate: (tab: AppTab) => void;
  crisisData: CrisisDataState;
}) {
  if (phase === 'refreshing') {
    return <RefreshingContent refresh={crisisData.refresh} onComplete={() => setPhase('no-crisis')} />;
  }

  return (
    <View style={{ flex: 1 }}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        {phase === 'no-crisis' ? (
          <NoCrisisContent crisisData={crisisData} onRefresh={() => setPhase('refreshing')} />
        ) : (
          <CrisisContent
            phase={phase}
            onNavigate={onNavigate}
            onRefresh={() => setPhase('refreshing')}
            crisisData={crisisData}
          />
        )}
      </ScrollView>

      <ChatPrompt onPress={() => onNavigate('chat')} />
    </View>
  );
}

function Header({
  sync,
  onRefresh,
  location,
}: {
  sync: string;
  onRefresh: () => void;
  location: string;
}) {
  return (
    <View style={styles.header}>
      <View>
        <View style={styles.rowCenter}>
          <Text style={styles.locationIcon}>⌖</Text>
          <Text style={styles.locationText}>{location}</Text>
        </View>
        <Text style={styles.subtleText}>{sync}</Text>
      </View>
      <Pressable onPress={onRefresh} style={styles.refreshButton}>
        <Text style={styles.refreshText}>↻ Refresh</Text>
      </Pressable>
    </View>
  );
}

function CrisisContent({
  phase,
  onNavigate,
  onRefresh,
  crisisData,
}: {
  phase: 'crisis' | 'updated';
  onNavigate: (tab: AppTab) => void;
  onRefresh: () => void;
  crisisData: CrisisDataState;
}) {
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const isUpdated = phase === 'updated';
  const acres = isUpdated ? '4,200' : '3,100';
  const contained = isUpdated ? '25%' : '15%';
  const changes = isUpdated
    ? [
        'Fire grew by 1,100 acres (now 4,200 total)',
        'Evacuation warning expanded south',
        'New road closure reported on Almaden Expwy',
        'Your evacuation status is unchanged',
      ]
    : [
        'Canyon Fire reported by CAL FIRE',
        'Evacuation warning issued for nearby zones',
        'Wind shift reported — monitoring conditions',
        'No road closures affecting your area yet',
      ];

  return (
    <View>
      <Header
        sync={syncLabel(crisisData)}
        onRefresh={onRefresh}
        location={locationLabel(crisisData)}
      />

      <CrisisMap compact layers={defaultLayers} location={crisisData.snapshot?.location ?? null} features={crisisData.snapshot?.features ?? []} loading={crisisData.loading} stale={crisisData.snapshot?.stale} onExpandMap={() => onNavigate('map')} />

      <View style={styles.card}>
        <View style={styles.cardPadded}>
          <StatusBadge level="PREPARE" />
          <Text style={styles.bodyText}>
            An evacuation warning has been issued nearby. Your current location
            is not under an evacuation order.
          </Text>
        </View>
        <Divider />
        <InfoBlock
          accent={COLORS.navy}
          title="Official Status"
          body="Evacuation warning nearby"
          caption="Source: Santa Clara County Emergency Management"
        />
        <Divider />
        <InfoBlock
          accent="#6366F1"
          title="Suggested action plan"
          body="Generated by your crisis agent"
          caption="Not official guidance"
        />
        <View style={styles.fireStrip}>
          <View>
            <Text style={styles.fireTitle}>Canyon Fire</Text>
            <Text style={styles.subtleText}>
              {acres} acres · {contained} contained
            </Text>
          </View>
          <View>
            <Text style={styles.distanceText}>8.4 mi away</Text>
            <Text style={styles.subtleText}>NE of your location</Text>
          </View>
        </View>
      </View>

      <SectionLabel>What to do now</SectionLabel>
      <View style={styles.card}>
        {[
          'Gather identification and essential medications',
          'Charge your phone and backup battery',
          'Keep essential belongings ready to go',
          'Continue monitoring evacuation updates',
        ].map((text, index) => (
          <ActionItem key={text} text={text} index={index} />
        ))}
      </View>

      <SectionLabel>Since your last refresh</SectionLabel>
      <View style={styles.card}>
        {changes.map(text => (
          <ChangeItem key={text} text={text} />
        ))}
      </View>

      <Pressable
        onPress={() => setSourcesOpen(open => !open)}
        style={[styles.card, styles.sourcesButton]}>
        <Text style={styles.sourceButtonText}>ⓘ Sources & attribution</Text>
        <Text style={styles.chevron}>{sourcesOpen ? '⌃' : '⌄'}</Text>
      </Pressable>
      {sourcesOpen && (
        <View style={[styles.card, styles.sourcesList]}>
          <SourceTag name="Santa Clara County OES" time="8 min ago" />
          <SourceTag name="CAL FIRE — Canyon Fire" time="8 min ago" />
          <SourceTag name="NWS Bay Area" time="12 min ago" />
          <SourceTag name="511 SF Bay — Road Closures" time="22 min ago" />
        </View>
      )}
    </View>
  );
}

function NoCrisisContent({ onRefresh, crisisData }: { onRefresh: () => void; crisisData: CrisisDataState }) {
  const features = crisisData.snapshot?.features ?? [];
  const unavailable = crisisData.snapshot
    ? Object.values(crisisData.snapshot.sourceHealth).filter(source => source.status === 'error').length
    : 2;
  return (
    <View>
      <Header sync={syncLabel(crisisData)} location={locationLabel(crisisData)} onRefresh={onRefresh} />
      <CrisisMap
        compact
        layers={defaultLayers}
        location={crisisData.snapshot?.location ?? null}
        features={crisisData.snapshot?.features ?? []}
        loading={crisisData.loading}
        stale={crisisData.snapshot?.stale}
      />
      <View style={[styles.card, styles.clearCard]}>
        <View style={styles.clearIcon}>
          <Text style={styles.clearCheck}>✓</Text>
        </View>
        <View style={styles.flex}>
          <StatusBadge level="CLEAR" />
          <Text style={styles.clearText}>{features.length ? `${features.length} official map feature${features.length === 1 ? '' : 's'} found` : unavailable ? 'Live sources are currently unavailable' : 'No mapped threats found for your location'}</Text>
        </View>
      </View>
      <SectionLabel>Nearby activity</SectionLabel>
      <View style={styles.card}>
        {features.length ? features.slice(0, 5).map(feature => (
          <View key={feature.id} style={styles.activityItem}>
            <Text style={styles.activityMark}>•</Text>
            <View style={styles.flex}>
              <Text style={styles.activityTitle}>{feature.title}</Text>
              <Text style={styles.subtleText}>{feature.sourceName} · {new Date(feature.updatedAt).toLocaleString()}</Text>
            </View>
          </View>
        )) : <View style={styles.activityItem}><Text style={styles.subtleText}>{unavailable ? 'Refresh again later. Missing data is never treated as an all-clear.' : 'Official sources returned no mapped features for this point.'}</Text></View>}
      </View>
    </View>
  );
}

function RefreshingContent({ onComplete, refresh }: { onComplete: () => void; refresh: () => Promise<void> }) {
  const [visibleSteps, setVisibleSteps] = useState(0);
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => {
    const timings = [400, 900, 1500, 2100, 2700];
    const timers = timings.map((delay, index) =>
      setTimeout(() => {
        setVisibleSteps(index + 1);
        setCurrentStep(index);
      }, delay),
    );
    let cancelled = false;
    const started = Date.now();
    refresh().finally(() => {
      const remaining = Math.max(0, 1000 - (Date.now() - started));
      setTimeout(() => { if (!cancelled) onComplete(); }, remaining);
    });

    return () => {
      timers.forEach(clearTimeout);
      cancelled = true;
    };
  }, [onComplete, refresh]);

  return (
    <View style={styles.refreshingScreen}>
      <View style={styles.refreshLocation}>
        <Text style={styles.locationIcon}>⌖</Text>
        <Text style={styles.locationText}>San Jose, CA</Text>
      </View>
      <View style={styles.bigSpinner}>
        <ActivityIndicator color={COLORS.navy} size="large" />
      </View>
      <Text style={styles.refreshTitle}>Checking your area</Text>
      <Text style={styles.refreshCaption}>
        Your crisis agent is consulting official sources
      </Text>

      <View style={styles.steps}>
        {REFRESH_STEPS.slice(0, visibleSteps).map((step, index) => {
          const done = index < currentStep;
          const active = index === currentStep;

          return (
            <View key={step} style={styles.stepRow}>
              <View
                style={[
                  styles.stepDot,
                  done && styles.stepDone,
                  active && styles.stepActive,
                ]}>
                {done && <Text style={styles.stepCheck}>✓</Text>}
              </View>
              <Text style={[styles.stepText, active && styles.stepTextActive]}>
                {step}
              </Text>
            </View>
          );
        })}
      </View>
    </View>
  );
}
