import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, Text, View } from 'react-native';
import { COLORS, REFRESH_STEPS } from '../constants';
import { styles } from '../styles';
import type { AppTab, HomePhase } from '../types';
import CrisisMap from '../components/CrisisMap';
import ChatPrompt from '../components/ChatPrompt';
import { ActionItem, ChangeItem, Divider, InfoBlock, SectionLabel, SourceTag, StatusBadge } from '../components/common';

export default function HomeScreen({
  phase,
  setPhase,
  onNavigate,
}: {
  phase: HomePhase;
  setPhase: (phase: HomePhase) => void;
  onNavigate: (tab: AppTab) => void;
}) {
  if (phase === 'refreshing') {
    return <RefreshingContent onComplete={() => setPhase('updated')} />;
  }

  return (
    <View style={{ flex: 1 }}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        {phase === 'no-crisis' ? (
          <NoCrisisContent onRefresh={() => setPhase('refreshing')} />
        ) : (
          <CrisisContent
            phase={phase}
            onNavigate={onNavigate}
            onRefresh={() => setPhase('refreshing')}
          />
        )}
      </ScrollView>

      <ChatPrompt onPress={() => onNavigate('chat')} />
    </View>
  );
}

function Header({
  sync,
  onRefresh,
}: {
  sync: string;
  onRefresh: () => void;
}) {
  return (
    <View style={styles.header}>
      <View>
        <View style={styles.rowCenter}>
          <Text style={styles.locationIcon}>⌖</Text>
          <Text style={styles.locationText}>San Jose, CA</Text>
        </View>
        <Text style={styles.subtleText}>{sync}</Text>
      </View>
      <Pressable onPress={onRefresh} style={styles.refreshButton}>
        <Text style={styles.refreshText}>↻ Refresh</Text>
      </Pressable>
    </View>
  );
}

function CrisisContent({
  phase,
  onNavigate,
  onRefresh,
}: {
  phase: 'crisis' | 'updated';
  onNavigate: (tab: AppTab) => void;
  onRefresh: () => void;
}) {
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const isUpdated = phase === 'updated';
  const acres = isUpdated ? '4,200' : '3,100';
  const contained = isUpdated ? '25%' : '15%';
  const changes = isUpdated
    ? [
        'Fire grew by 1,100 acres (now 4,200 total)',
        'Evacuation warning expanded south',
        'New road closure reported on Almaden Expwy',
        'Your evacuation status is unchanged',
      ]
    : [
        'Canyon Fire reported by CAL FIRE',
        'Evacuation warning issued for nearby zones',
        'Wind shift reported — monitoring conditions',
        'No road closures affecting your area yet',
      ];

  return (
    <View>
      <Header
        sync={`${isUpdated ? 'Updated' : 'Last synced'} ${
          isUpdated ? 'Just now' : '2:14 PM'
        }`}
        onRefresh={onRefresh}
      />

      <CrisisMap compact onExpandMap={() => onNavigate('map')} />

      <View style={styles.card}>
        <View style={styles.cardPadded}>
          <StatusBadge level="PREPARE" />
          <Text style={styles.bodyText}>
            An evacuation warning has been issued nearby. Your current location
            is not under an evacuation order.
          </Text>
        </View>
        <Divider />
        <InfoBlock
          accent={COLORS.navy}
          title="Official Status"
          body="Evacuation warning nearby"
          caption="Source: Santa Clara County Emergency Management"
        />
        <Divider />
        <InfoBlock
          accent="#6366F1"
          title="Suggested action plan"
          body="Generated by your crisis agent"
          caption="Not official guidance"
        />
        <View style={styles.fireStrip}>
          <View>
            <Text style={styles.fireTitle}>Canyon Fire</Text>
            <Text style={styles.subtleText}>
              {acres} acres · {contained} contained
            </Text>
          </View>
          <View>
            <Text style={styles.distanceText}>8.4 mi away</Text>
            <Text style={styles.subtleText}>NE of your location</Text>
          </View>
        </View>
      </View>

      <SectionLabel>What to do now</SectionLabel>
      <View style={styles.card}>
        {[
          'Gather identification and essential medications',
          'Charge your phone and backup battery',
          'Keep essential belongings ready to go',
          'Continue monitoring evacuation updates',
        ].map((text, index) => (
          <ActionItem key={text} text={text} index={index} />
        ))}
      </View>

      <SectionLabel>Since your last refresh</SectionLabel>
      <View style={styles.card}>
        {changes.map(text => (
          <ChangeItem key={text} text={text} />
        ))}
      </View>

      <Pressable
        onPress={() => setSourcesOpen(open => !open)}
        style={[styles.card, styles.sourcesButton]}>
        <Text style={styles.sourceButtonText}>ⓘ Sources & attribution</Text>
        <Text style={styles.chevron}>{sourcesOpen ? '⌃' : '⌄'}</Text>
      </Pressable>
      {sourcesOpen && (
        <View style={[styles.card, styles.sourcesList]}>
          <SourceTag name="Santa Clara County OES" time="8 min ago" />
          <SourceTag name="CAL FIRE — Canyon Fire" time="8 min ago" />
          <SourceTag name="NWS Bay Area" time="12 min ago" />
          <SourceTag name="511 SF Bay — Road Closures" time="22 min ago" />
        </View>
      )}
    </View>
  );
}

function NoCrisisContent({ onRefresh }: { onRefresh: () => void }) {
  return (
    <View>
      <Header sync="Last checked 2:14 PM" onRefresh={onRefresh} />
      <CrisisMap
        compact
        layers={{
          myLocation: true,
          wildfire: false,
          evacWarning: false,
          evacOrder: false,
        }}
      />
      <View style={[styles.card, styles.clearCard]}>
        <View style={styles.clearIcon}>
          <Text style={styles.clearCheck}>✓</Text>
        </View>
        <View style={styles.flex}>
          <StatusBadge level="CLEAR" />
          <Text style={styles.clearText}>No immediate threats found near you</Text>
        </View>
      </View>
      <SectionLabel>Nearby activity</SectionLabel>
      <View style={styles.card}>
        {[
          ['M3.1 earthquake — 47 miles away', 'No action needed · 38 min ago'],
          ['Red flag warning — high fire risk', 'Dry winds through Thursday · NWS'],
          ['Minor coastal flooding advisory', 'Santa Cruz area · Not near you'],
        ].map(([title, sub]) => (
          <View key={title} style={styles.activityItem}>
            <Text style={styles.activityMark}>•</Text>
            <View style={styles.flex}>
              <Text style={styles.activityTitle}>{title}</Text>
              <Text style={styles.subtleText}>{sub}</Text>
            </View>
          </View>
        ))}
      </View>
    </View>
  );
}

function RefreshingContent({ onComplete }: { onComplete: () => void }) {
  const [visibleSteps, setVisibleSteps] = useState(0);
  const [currentStep, setCurrentStep] = useState(0);

  useEffect(() => {
    const timings = [400, 900, 1500, 2100, 2700];
    const timers = timings.map((delay, index) =>
      setTimeout(() => {
        setVisibleSteps(index + 1);
        setCurrentStep(index);
      }, delay),
    );
    const doneTimer = setTimeout(onComplete, 3600);

    return () => {
      timers.forEach(clearTimeout);
      clearTimeout(doneTimer);
    };
  }, [onComplete]);

  return (
    <View style={styles.refreshingScreen}>
      <View style={styles.refreshLocation}>
        <Text style={styles.locationIcon}>⌖</Text>
        <Text style={styles.locationText}>San Jose, CA</Text>
      </View>
      <View style={styles.bigSpinner}>
        <ActivityIndicator color={COLORS.navy} size="large" />
      </View>
      <Text style={styles.refreshTitle}>Checking your area</Text>
      <Text style={styles.refreshCaption}>
        Your crisis agent is consulting official sources
      </Text>

      <View style={styles.steps}>
        {REFRESH_STEPS.slice(0, visibleSteps).map((step, index) => {
          const done = index < currentStep;
          const active = index === currentStep;

          return (
            <View key={step} style={styles.stepRow}>
              <View
                style={[
                  styles.stepDot,
                  done && styles.stepDone,
                  active && styles.stepActive,
                ]}>
                {done && <Text style={styles.stepCheck}>✓</Text>}
              </View>
              <Text style={[styles.stepText, active && styles.stepTextActive]}>
                {step}
              </Text>
            </View>
          );
        })}
      </View>
    </View>
  );
}
