import { StyleSheet } from 'react-native';
import { COLORS } from './constants';
import type { LayerKey } from './types';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: COLORS.paper,
  },
  screen: {
    flex: 1,
    backgroundColor: COLORS.paper,
  },
  scrollContent: {
    paddingBottom: 22,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  rowCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  locationIcon: {
    color: COLORS.blue,
    fontSize: 14,
    fontWeight: '800',
  },
  locationText: {
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '700',
  },
  subtleText: {
    color: COLORS.muted,
    fontSize: 11,
    marginTop: 3,
  },
  refreshButton: {
    backgroundColor: COLORS.navy,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  refreshText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  card: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: COLORS.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#EEEAE3',
    overflow: 'hidden',
  },
  cardPadded: {
    padding: 16,
  },
  badge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    gap: 6,
  },
  badgeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  bodyText: {
    color: COLORS.body,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 9,
  },
  divider: {
    height: 1,
    backgroundColor: '#F0EDE8',
    marginHorizontal: 16,
  },
  infoBlock: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  infoTitle: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 5,
  },
  infoBody: {
    color: COLORS.body,
    fontSize: 12,
    fontWeight: '700',
  },
  fireStrip: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FDF7EE',
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  fireTitle: {
    color: COLORS.orange,
    fontSize: 13,
    fontWeight: '800',
  },
  distanceText: {
    color: COLORS.body,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
  },
  sectionLabel: {
    color: COLORS.muted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 2,
  },
  actionItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDE8',
  },
  actionIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.soft,
  },
  actionIconText: {
    color: COLORS.body,
    fontSize: 10,
    fontWeight: '800',
  },
  actionText: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 13,
    lineHeight: 18,
    paddingTop: 5,
  },
  changeItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  changeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.orange,
    marginTop: 7,
  },
  changeText: {
    flex: 1,
    color: COLORS.body,
    fontSize: 13,
    lineHeight: 18,
  },
  sourcesButton: {
    paddingHorizontal: 16,
    paddingVertical: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sourceButtonText: {
    color: COLORS.body,
    fontSize: 12,
    fontWeight: '800',
  },
  chevron: {
    color: COLORS.muted,
    fontSize: 16,
  },
  sourcesList: {
    marginTop: 4,
    paddingHorizontal: 16,
  },
  sourceTag: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDE8',
  },
  sourceName: {
    color: COLORS.body,
    fontSize: 12,
    fontWeight: '700',
  },
  clearCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
  },
  clearIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5F5EE',
  },
  clearCheck: {
    color: COLORS.green,
    fontSize: 20,
    fontWeight: '900',
  },
  clearText: {
    color: COLORS.body,
    fontSize: 13,
    fontWeight: '700',
    marginTop: 6,
  },
  activityItem: {
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDE8',
  },
  activityMark: {
    color: COLORS.orange,
    fontSize: 22,
    lineHeight: 22,
  },
  activityTitle: {
    color: COLORS.body,
    fontSize: 13,
    fontWeight: '700',
  },
  flex: {
    flex: 1,
  },
  refreshingScreen: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 40,
    alignItems: 'center',
  },
  refreshLocation: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 36,
  },
  bigSpinner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#EBF0F7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  refreshTitle: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  refreshCaption: {
    color: COLORS.muted,
    fontSize: 12,
    textAlign: 'center',
    marginTop: 5,
    marginBottom: 28,
  },
  steps: {
    width: '100%',
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0EDE8',
  },
  stepDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: COLORS.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDone: {
    backgroundColor: COLORS.green,
    borderColor: COLORS.green,
  },
  stepActive: {
    borderColor: COLORS.navy,
  },
  stepCheck: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
  },
  stepText: {
    color: COLORS.body,
    fontSize: 13,
  },
  stepTextActive: {
    color: COLORS.ink,
    fontWeight: '700',
  },
  mapScreen: {
    flex: 1,
    backgroundColor: COLORS.paper,
  },
  mapToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  roundButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.soft,
  },
  roundButtonText: {
    color: COLORS.ink,
    fontSize: 24,
    lineHeight: 26,
  },
  toolbarTitle: {
    color: COLORS.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  fullMapArea: {
    flex: 1,
    position: 'relative',
  },
  layerWrap: {
    position: 'absolute',
    top: 12,
    left: 12,
    right: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  layerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  layerChipInactive: {
    borderColor: COLORS.line,
  },
  layerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  layerDotInactive: {
    backgroundColor: '#D0CCC4',
  },
  layerText: {
    fontSize: 11,
    fontWeight: '800',
  },
  layerTextInactive: {
    color: COLORS.muted,
  },
  tapHint: {
    position: 'absolute',
    bottom: 16,
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  tapHintText: {
    color: '#5A5E68',
    fontSize: 11,
    fontWeight: '700',
  },
  bottomSheet: {
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingBottom: 20,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 32,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.line,
    marginVertical: 10,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sheetTitle: {
    color: COLORS.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  closeButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.soft,
  },
  closeText: {
    color: COLORS.muted,
    fontSize: 20,
    lineHeight: 22,
  },
  sheetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    paddingVertical: 5,
  },
  sheetLabel: {
    color: COLORS.muted,
    fontSize: 12,
  },
  sheetValue: {
    flex: 1,
    color: COLORS.ink,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  sheetSource: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0EDE8',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  sheetSourceText: {
    flex: 1,
    color: COLORS.muted,
    fontSize: 10,
  },
  crisisMap: {
    width: '100%',
    backgroundColor: '#DED9CF',
    overflow: 'hidden',
    position: 'relative',
  },
  compactMap: {
    height: 192,
  },
  largeMap: {
    flex: 1,
  },
  mapBlockA: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: '38%',
    height: '45%',
    backgroundColor: '#D8D3C9',
  },
  mapBlockB: {
    position: 'absolute',
    left: '40%',
    top: 0,
    width: '28%',
    height: '70%',
    backgroundColor: '#D8D3C9',
  },
  mapBlockC: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: '32%',
    height: '48%',
    backgroundColor: '#D8D3C9',
  },
  mapParkOne: {
    position: 'absolute',
    left: 18,
    top: 18,
    width: 72,
    height: 64,
    backgroundColor: '#C2D9A8',
    transform: [{ rotate: '2deg' }],
  },
  mapParkTwo: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 68,
    height: 54,
    backgroundColor: '#C2D9A8',
  },
  creek: {
    position: 'absolute',
    left: '41%',
    top: 36,
    width: 4,
    height: '72%',
    borderRadius: 2,
    backgroundColor: '#A4C4DA',
    transform: [{ rotate: '4deg' }],
  },
  roadH: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#F0EDE5',
  },
  roadV: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: '#F0EDE5',
  },
  diagonalRoad: {
    position: 'absolute',
    left: -30,
    bottom: 80,
    width: '120%',
    height: 10,
    borderRadius: 5,
    backgroundColor: '#EDE8DF',
    transform: [{ rotate: '-32deg' }],
  },
  zone: {
    position: 'absolute',
    borderWidth: 2,
    borderStyle: 'dashed',
  },
  warningZone: {
    top: -20,
    right: -40,
    width: '76%',
    height: '96%',
    borderColor: COLORS.orange,
    backgroundColor: 'rgba(201,123,14,0.09)',
    transform: [{ rotate: '-4deg' }],
  },
  orderZone: {
    top: 30,
    right: 28,
    width: '31%',
    height: '29%',
    borderColor: COLORS.red,
    backgroundColor: 'rgba(196,53,53,0.1)',
    transform: [{ rotate: '9deg' }],
  },
  firePerimeter: {
    position: 'absolute',
    top: 46,
    right: 52,
    width: 66,
    height: 52,
    borderRadius: 28,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#DC5012',
    backgroundColor: 'rgba(220,80,18,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fireMarker: {
    color: '#DC5012',
    fontSize: 24,
    fontWeight: '900',
  },
  distanceLine: {
    position: 'absolute',
    left: '38%',
    top: '41%',
    width: '42%',
    height: 1,
    borderTopWidth: 1,
    borderTopColor: '#8A8E96',
    transform: [{ rotate: '-38deg' }],
    opacity: 0.55,
  },
  distanceBadge: {
    position: 'absolute',
    left: '53%',
    top: '43%',
    backgroundColor: 'rgba(255,255,255,0.86)',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  distanceBadgeText: {
    color: '#5A5E68',
    fontSize: 9,
    fontWeight: '800',
  },
  myLocation: {
    position: 'absolute',
    left: '36%',
    top: '70%',
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: COLORS.blue,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  myLocationInner: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  legend: {
    position: 'absolute',
    left: 8,
    bottom: 8,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderRadius: 6,
    padding: 7,
    gap: 4,
  },
  legendRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendSwatch: {
    width: 10,
    height: 6,
    borderRadius: 1,
  },
  legendText: {
    color: '#5A5E68',
    fontSize: 8,
    fontWeight: '700',
  },
  expandButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.92)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  expandText: {
    color: COLORS.ink,
    fontSize: 11,
    fontWeight: '800',
  },
  attribution: {
    position: 'absolute',
    right: 10,
    bottom: 6,
    color: 'rgba(255,255,255,0.85)',
    fontSize: 9,
    fontWeight: '700',
  },
  chatScreen: {
    flex: 1,
    backgroundColor: COLORS.paper,
  },
  chatHeader: {
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  chatTitle: {
    color: COLORS.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  onlineText: {
    color: COLORS.green,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 4,
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    padding: 16,
    gap: 14,
  },
  messageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  assistantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: COLORS.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '900',
  },
  messageBubble: {
    maxWidth: '80%',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  assistantBubble: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderBottomLeftRadius: 4,
  },
  userBubble: {
    backgroundColor: COLORS.navy,
    borderBottomRightRadius: 4,
  },
  messageText: {
    color: COLORS.ink,
    fontSize: 13,
    lineHeight: 19,
  },
  userMessageText: {
    color: '#FFFFFF',
  },
  messageSource: {
    color: COLORS.muted,
    fontSize: 10,
    marginTop: 7,
  },
  typingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  typingBubble: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  suggestions: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  suggestionTitle: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  promptWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  promptChip: {
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  promptText: {
    color: COLORS.ink,
    fontSize: 12,
    fontWeight: '700',
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  input: {
    flex: 1,
    minHeight: 40,
    backgroundColor: COLORS.soft,
    borderRadius: 20,
    paddingHorizontal: 14,
    color: COLORS.ink,
    fontSize: 13,
  },
  sendButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonReady: {
    backgroundColor: COLORS.navy,
  },
  sendText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
  },
  bottomNav: {
    height: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: COLORS.card,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingBottom: 14,
    paddingTop: 8,
  },
  navItem: {
    minWidth: 76,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    paddingVertical: 3,
  },
  navIcon: {
    color: COLORS.muted,
    fontSize: 21,
    fontWeight: '800',
  },
  navLabel: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: '800',
  },
  navActive: {
    color: COLORS.navy,
  },
  errorBox: {
    margin: 16,
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
  },
  errorTitle: {
    color: COLORS.red,
    fontWeight: '900',
    marginBottom: 4,
  },
  errorText: {
    color: COLORS.red,
    fontSize: 12,
  },
});

export const layerChipStyles = StyleSheet.create<Record<LayerKey, { borderColor: string }>>({
  myLocation: { borderColor: COLORS.blue },
  wildfire: { borderColor: '#DC5012' },
  evacWarning: { borderColor: COLORS.orange },
  evacOrder: { borderColor: COLORS.red },
});

export const layerDotStyles = StyleSheet.create<Record<LayerKey, { backgroundColor: string }>>({
  myLocation: { backgroundColor: COLORS.blue },
  wildfire: { backgroundColor: '#DC5012' },
  evacWarning: { backgroundColor: COLORS.orange },
  evacOrder: { backgroundColor: COLORS.red },
});

export const layerTextStyles = StyleSheet.create<Record<LayerKey, { color: string }>>({
  myLocation: { color: COLORS.blue },
  wildfire: { color: '#DC5012' },
  evacWarning: { color: COLORS.orange },
  evacOrder: { color: COLORS.red },
});

